# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Driver Uber' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Driver Uber
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
end
